package models

import (
	"time"

	"github.com/google/uuid"
	"gorm.io/datatypes"
)

type Flow struct {
	ID           int    `gorm:"primaryKey" json:"id"`
	Name         string `json:"name"`
	TriggerType  string `gorm:"column:triggerType" json:"triggerType"`
	TriggerValue string `gorm:"column:triggerValue" json:"triggerValue"`
	// TriggerOperator refines keyword matching beyond exact-equals (the
	// historical default when empty): contains|starts_with|ends_with|regex.
	// See flow.ValidTriggerOperators.
	TriggerOperator string         `gorm:"column:triggerOperator" json:"triggerOperator"`
	Nodes           datatypes.JSON `gorm:"type:json" json:"nodes"`
	Edges           datatypes.JSON `gorm:"type:json" json:"edges"`
	Active          bool           `json:"active"`
	// Internal marks a Flow generated by a plugin (currently "Assistentes de
	// IA", ADR 0027) as an implementation detail — hidden from the normal
	// Flow listing/UI, never user-authored, never edited by hand.
	Internal   bool      `gorm:"default:false" json:"internal"`
	WhatsAppID *int      `gorm:"column:whatsappId" json:"whatsappId"`
	TenantID   uuid.UUID `gorm:"column:tenantId;type:uuid" json:"tenantId"`
	CreatedAt  time.Time `gorm:"column:createdAt" json:"createdAt"`
	UpdatedAt  time.Time `gorm:"column:updatedAt" json:"updatedAt"`

	// Whatsapp is the connection this flow is bound to (channel binding).
	// Preloaded by List/Show/Create/Update so the API exposes the connection name.
	Whatsapp *Whatsapp `gorm:"foreignKey:WhatsAppID" json:"whatsapp,omitempty"`
}

func (Flow) TableName() string {
	return "Flows"
}
