package flow

import (
	"context"
	"encoding/json"

	"github.com/alltomatos/watinkdev/business/internal/models"
)

// AssistantRuntime is implemented by the "Assistentes de IA" plugin and
// injected into ExecState (never imported by this package — ADR 0027,
// avoids a flow↔plugins dependency cycle). It runs one turn of the Assistant
// identified by assistantID for the current inbound message.
type AssistantRuntime interface {
	Execute(ctx context.Context, st *ExecState, assistantID int) (Outcome, error)
}

// FlowStarter starts a Flow's FlowRun for the same ticket that triggered the
// current pass — used by AssistantRuntime implementations to hand off from a
// synthetic Assistant Flow to another Flow (router mode delegating to a
// target Assistant's own synthetic Flow, or Assistant mode "flow" delegating
// to a user-authored Flow). Skeleton satisfies this interface.
type FlowStarter interface {
	StartFlow(ctx context.Context, in InboundContext, f models.Flow) error
}

// assistantData is the synthetic "assistant" node envelope generated by the
// plugin (see docs/agents/assistants.md) — carries only the Assistant's ID,
// the plugin resolves everything else (Mode, Config) by loading the row.
type assistantData struct {
	AssistantID int `json:"assistantId"`
}

// assistantExecutor delegates a synthetic Assistant Flow's single node to the
// plugin's runtime. Degrades gracefully (advances) when no runtime is wired
// or the node data is malformed — mirrors agentExecutor/knowledgeExecutor's
// posture: a misconfigured node never aborts the run.
type assistantExecutor struct{}

func (assistantExecutor) Type() string { return string(NodeAssistant) }

// SendAssistantText sends a text message on behalf of an AssistantRuntime
// implementation, reusing the same outbound path (channel adapter, EnvID
// dedup) as every other node — exported because AssistantRuntime lives
// outside this package (ADR 0027). suffix disambiguates multiple sends
// within the same node/turn (e.g. "menu", "t3") so the adapter's 24h EnvID
// dedup lock never collapses them.
//
// Meta["humanPacing"]=true tells WhatsAppAdapter.Send to show "digitando..."
// and wait a delay proportional to len(body) before actually sending — a
// human doesn't type a 5000-word reply in 2 seconds. Scoped to Assistant
// sends only (not FlowBuilder text nodes in general).
func SendAssistantText(ctx context.Context, st *ExecState, suffix, body string) error {
	return sendWhatsAppEnv(ctx, st, envIDWithSuffix(st, "assistant-node", suffix), body, map[string]any{"humanPacing": true})
}

func (assistantExecutor) Execute(ctx context.Context, st *ExecState, node Node) (Outcome, error) {
	var d assistantData
	if len(node.Data) > 0 {
		_ = json.Unmarshal(node.Data, &d)
	}
	if d.AssistantID == 0 || st.AssistantRuntime == nil {
		return Outcome{Kind: OutcomeAdvance, Detail: "assistant: sem assistantId/runtime"}, nil
	}
	return st.AssistantRuntime.Execute(ctx, st, d.AssistantID)
}
